package act6_grp8;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

class GradeEncoding extends javax.swing.JFrame {

    /**
     * Creates new form GradeEncoding
     */
    public GradeEncoding() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastnameTF = new javax.swing.JTextField();
        studentnumberTF = new javax.swing.JTextField();
        firstnameTF = new javax.swing.JTextField();
        middlenameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sectionnameCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sinesosUnits = new javax.swing.JTextField();
        purcomUnits = new javax.swing.JTextField();
        mmwUnits = new javax.swing.JTextField();
        comprogUnits = new javax.swing.JTextField();
        assemblyUnits = new javax.swing.JTextField();
        discreteUnits = new javax.swing.JTextField();
        aquaticsUnits = new javax.swing.JTextField();
        nstpUnits = new javax.swing.JTextField();
        sinesosGrade = new javax.swing.JComboBox<>();
        purcomGrade = new javax.swing.JComboBox<>();
        mmwGrade = new javax.swing.JComboBox<>();
        comprogGrade = new javax.swing.JComboBox<>();
        assemblyGrade = new javax.swing.JComboBox<>();
        discreteGrade = new javax.swing.JComboBox<>();
        aquaticsGrade = new javax.swing.JComboBox<>();
        nstpGrade = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        calcGWA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtFinalGrade = new javax.swing.JTextField();
        sinesosRemark = new javax.swing.JLabel();
        purcomRemark = new javax.swing.JLabel();
        mmwRemark = new javax.swing.JLabel();
        comprogRemark = new javax.swing.JLabel();
        assemblyRemark = new javax.swing.JLabel();
        discreteRemark = new javax.swing.JLabel();
        aquaticsRemark = new javax.swing.JLabel();
        nstpRemark = new javax.swing.JLabel();
        finalgwaRemark = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Grade Encoding");

        jLabel2.setText("Student No.:");

        jLabel3.setText("Student Name:");

        middlenameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middlenameTFActionPerformed(evt);
            }
        });

        jLabel4.setText("Section Name:");

        sectionnameCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SD1A", "SD1B" }));

        jLabel5.setText("Last Name");

        jLabel6.setText("First Name");

        jLabel7.setText("Middle Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Course Title");

        jLabel9.setText("SineSosyedad/Pelikulang Panlipunan (SINESOS)");

        jLabel10.setText("Purposive Communication");

        jLabel11.setText("Mathematics in the Modern World");

        jLabel12.setText("Computer Programming II");

        jLabel13.setText("Computer Organization and Architecture with Assembly Programming");

        jLabel14.setText("Discrete Math II");

        jLabel15.setText("Aquatics");

        jLabel16.setText("National Service Training Program II");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Units");

        sinesosUnits.setEditable(false);
        sinesosUnits.setText("3");

        purcomUnits.setEditable(false);
        purcomUnits.setText("3");

        mmwUnits.setEditable(false);
        mmwUnits.setText("3");

        comprogUnits.setEditable(false);
        comprogUnits.setText("3");

        assemblyUnits.setEditable(false);
        assemblyUnits.setText("3");

        discreteUnits.setEditable(false);
        discreteUnits.setText("3");

        aquaticsUnits.setEditable(false);
        aquaticsUnits.setText("2");

        nstpUnits.setEditable(false);
        nstpUnits.setText("3");

        sinesosGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));
        sinesosGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinesosGradeActionPerformed(evt);
            }
        });

        purcomGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));

        mmwGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));

        comprogGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));

        assemblyGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));

        discreteGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));

        aquaticsGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));

        nstpGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.5", "2.75", "3.0", "4.0", "5.0" }));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Grades");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Remarks");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        calcGWA.setText("Calculate GWA");
        calcGWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcGWAActionPerformed(evt);
            }
        });

        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student No.", "Student Name", "GWA", "Remarks"
            }
        ));
        jScrollPane1.setViewportView(infoTable);

        jLabel20.setText("Final Grade:");

        txtFinalGrade.setEditable(false);

        sinesosRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        purcomRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mmwRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        comprogRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        assemblyRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        discreteRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        aquaticsRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        nstpRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        finalgwaRemark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(middlenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(255, 255, 255))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(calcGWA)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(153, 153, 153))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentnumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sectionnameCB, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(aquaticsUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(aquaticsGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(discreteUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(discreteGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(assemblyUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(assemblyGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(comprogUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(comprogGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(mmwUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(mmwGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(purcomUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(purcomGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sinesosUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(sinesosGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nstpUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(nstpGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFinalGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(119, 119, 119)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nstpRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aquaticsRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discreteRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(assemblyRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comprogRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mmwRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(purcomRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sinesosRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19)
                            .addComponent(finalgwaRemark, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentnumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sectionnameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middlenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sinesosUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinesosGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinesosRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(purcomUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purcomGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purcomRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mmwUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmwGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mmwRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comprogUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comprogGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comprogRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(assemblyUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assemblyGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assemblyRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(discreteUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discreteGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discreteRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(aquaticsUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aquaticsGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aquaticsRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nstpUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nstpGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nstpRemark))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtFinalGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalgwaRemark))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcGWA)
                    .addComponent(saveButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void middlenameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middlenameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middlenameTFActionPerformed

    private void calcGWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcGWAActionPerformed
        // Calculates the GWA and shows the Remarks
       
        //Sinesos Remarks
        if (sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(1) 
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(2)
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(3)
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(4)
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(5)
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(6)
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(7)
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(8)
                || sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(9)) 
        {
          sinesosRemark.setText(" PASSED ");
                    sinesosRemark.setForeground(Color.blue);
        }
        
        else if (sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(10))
        {
                sinesosRemark.setText("     INC ");
        sinesosRemark.setForeground(Color.red);
        }
        
        else if (sinesosGrade.getSelectedItem() == sinesosGrade.getItemAt(11))
        {
                sinesosRemark.setText(" FAILED ");
        sinesosRemark.setForeground(Color.red);
        }
        
        
        //PurCom Remarks
        if (purcomGrade.getSelectedItem() == purcomGrade.getItemAt(1) 
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(2)
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(3)
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(4)
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(5)
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(6)
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(7)
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(8)
                || purcomGrade.getSelectedItem() == purcomGrade.getItemAt(9)) 
        {
            purcomRemark.setText(" PASSED ");
                    purcomRemark.setForeground(Color.blue);
        }
        
        else if (purcomGrade.getSelectedItem() == purcomGrade.getItemAt(10))
        {
                purcomRemark.setText("     INC ");
        purcomRemark.setForeground(Color.red);
        }
        
        else if (purcomGrade.getSelectedItem() == purcomGrade.getItemAt(11))
        {
                purcomRemark.setText(" FAILED ");
        purcomRemark.setForeground(Color.red);
        }
        
        //MMW Remarks
         if (mmwGrade.getSelectedItem() == mmwGrade.getItemAt(1) 
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(2)
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(3)
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(4)
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(5)
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(6)
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(7)
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(8)
                || mmwGrade.getSelectedItem() == mmwGrade.getItemAt(9)) 
        {
            mmwRemark.setText(" PASSED ");
                    mmwRemark.setForeground(Color.blue);
        }
        
        else if (mmwGrade.getSelectedItem() == mmwGrade.getItemAt(10))
        {
                mmwRemark.setText("     INC ");
        mmwRemark.setForeground(Color.red);
        }
        
        else if (mmwGrade.getSelectedItem() == mmwGrade.getItemAt(11))
        {
                mmwRemark.setText(" FAILED ");
        mmwRemark.setForeground(Color.red);
        }
        
        //ComProg Remarks
        if (comprogGrade.getSelectedItem() == comprogGrade.getItemAt(1) 
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(2)
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(3)
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(4)
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(5)
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(6)
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(7)
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(8)
                || comprogGrade.getSelectedItem() == comprogGrade.getItemAt(9)) 
         {
            comprogRemark.setText(" PASSED ");
                    comprogRemark.setForeground(Color.blue);
        }
        
        else if (comprogGrade.getSelectedItem() == comprogGrade.getItemAt(10))
        {
                comprogRemark.setText("     INC ");
        comprogRemark.setForeground(Color.red);
        }
        
        else if (comprogGrade.getSelectedItem() == comprogGrade.getItemAt(11))
        {
                comprogRemark.setText(" FAILED ");
        comprogRemark.setForeground(Color.red);
        }
        
        //Assembly Remarks
        if (assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(1) 
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(2)
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(3)
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(4)
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(5)
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(6)
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(7)
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(8)
                || assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(9)) 
      {
            assemblyRemark.setText(" PASSED ");
                    assemblyRemark.setForeground(Color.blue);
        }
        
       else if (assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(10))
        {
                assemblyRemark.setText("     INC ");
        assemblyRemark.setForeground(Color.red);
        }
        
        else if (assemblyGrade.getSelectedItem() == assemblyGrade.getItemAt(11))
        {
                assemblyRemark.setText(" FAILED ");
        assemblyRemark.setForeground(Color.red);
        }
        
        //Discrete Remarks
        if (discreteGrade.getSelectedItem() == discreteGrade.getItemAt(1) 
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(2)
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(3)
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(4)
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(5)
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(6)
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(7)
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(8)
                || discreteGrade.getSelectedItem() == discreteGrade.getItemAt(9)) 
      {
            discreteRemark.setText(" PASSED ");
                    discreteRemark.setForeground(Color.blue);
        }
        
        else if (discreteGrade.getSelectedItem() == discreteGrade.getItemAt(10))
        {
                discreteRemark.setText("     INC ");
        discreteRemark.setForeground(Color.red);
        }
        
        else if (discreteGrade.getSelectedItem() == discreteGrade.getItemAt(11))
        {
                discreteRemark.setText(" FAILED ");
        discreteRemark.setForeground(Color.red);
        }
        
        //Aquatics Remark
        if (aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(1) 
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(2)
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(3)
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(4)
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(5)
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(6)
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(7)
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(8)
                || aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(9)) 
        {
            aquaticsRemark.setText(" PASSED ");
                    aquaticsRemark.setForeground(Color.blue);
        }
        
        else if (aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(10))
        {
                aquaticsRemark.setText("     INC ");
        aquaticsRemark.setForeground(Color.red);
        }
        
        else if (aquaticsGrade.getSelectedItem() == aquaticsGrade.getItemAt(11))
        {
                aquaticsRemark.setText(" FAILED ");
        aquaticsRemark.setForeground(Color.red);
        }
        
        //NSTP Remarks
         if (nstpGrade.getSelectedItem() == nstpGrade.getItemAt(1) 
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(2)
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(3)
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(4)
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(5)
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(6)
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(7)
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(8)
                || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(9)) 
       {
            nstpRemark.setText(" PASSED ");
                    nstpRemark.setForeground(Color.blue);
        }
        
        else if (nstpGrade.getSelectedItem() == nstpGrade.getItemAt(10))
        {
                nstpRemark.setText("     INC ");
        nstpRemark.setForeground(Color.red);
        }
        
        else if (nstpGrade.getSelectedItem() == nstpGrade.getItemAt(11))
        {
                nstpRemark.setText(" FAILED ");
        nstpRemark.setForeground(Color.red);
        }
    
        String sinesos = sinesosGrade.getSelectedItem().toString();
        String purcom = purcomGrade.getSelectedItem().toString();
        String mmw = mmwGrade.getSelectedItem().toString();
        String comprog = comprogGrade.getSelectedItem().toString();
        String assembly = assemblyGrade.getSelectedItem().toString();
        String discrete = discreteGrade.getSelectedItem().toString();
        String aquatics = aquaticsGrade.getSelectedItem().toString();
        String nstp = nstpGrade.getSelectedItem().toString();
        
        double sinesosFinal = Double.parseDouble(sinesos);
        double purcomFinal = Double.parseDouble(purcom);
        double mmwFinal = Double.parseDouble(mmw);
        double comprogFinal = Double.parseDouble(comprog);
        double assemblyFinal = Double.parseDouble(assembly);
        double discreteFinal = Double.parseDouble(discrete);
        double aquaticsFinal = Double.parseDouble(aquatics);
        double nstpFinal = Double.parseDouble(nstp);
        
        double units[] = {3.0, 2.0,};
        
        double sumGWA = ((sinesosFinal * units[0]) + 
                         (purcomFinal * units[0]) +
                         (mmwFinal * units[0]) + 
                         (comprogFinal * units[0]) +
                         (assemblyFinal * units[0]) + 
                         (discreteFinal * units[0]) +
                         (aquaticsFinal * units[1]) +
                         (nstpFinal * units[0]));
        
        double sumUnits = ((units[0] * 7) + units[1]);
        
        double finalGWA = (sumGWA / sumUnits);
        
        String finalGrade = String.format("%.5f", finalGWA);
        
        txtFinalGrade.setText(finalGrade);
        
        //GWA Remarks
         if (finalGWA >= 1.00000 && finalGWA <= 3.00000) 
       {
            finalgwaRemark.setText(" PASSED ");
                    finalgwaRemark.setForeground(Color.blue);
                    JOptionPane.showMessageDialog(this, "Looks like you've passed. Great work, keep it up!");
        }
        
        else if (finalGWA >= 4.00000 && finalGWA < 5.00000)
        {
                finalgwaRemark.setText("     INC ");
        finalgwaRemark.setForeground(Color.red);
        JOptionPane.showMessageDialog(this, "Looks like your grades are incomplete. You should go talk to your professor!");
        }
        
        else if (finalGWA == 5.00000)
        {
                finalgwaRemark.setText(" FAILED ");
        finalgwaRemark.setForeground(Color.red);
        JOptionPane.showMessageDialog(this, "Tanga!");
        }
        
        
    }//GEN-LAST:event_calcGWAActionPerformed

    private void sinesosGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinesosGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinesosGradeActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         if (nstpGrade.getSelectedItem() == nstpGrade.getItemAt(1) 
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(2)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(3)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(4)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(5)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(6)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(7)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(8)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(9)
             || nstpGrade.getSelectedItem() == nstpGrade.getItemAt(10)){

            showGradeRemark(); //opens remarks
            
        } else {
            showFixRemark(); //opens remark if has INC or FAILED
        }   
        
         
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void showGradeRemark() {
        javax.swing.JOptionPane.showMessageDialog(null, "Burat", getTitle(), javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    private void showFixRemark() {
        javax.swing.JOptionPane.showMessageDialog(null, "Tanga", "", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GradeEncoding().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aquaticsGrade;
    private javax.swing.JLabel aquaticsRemark;
    private javax.swing.JTextField aquaticsUnits;
    private javax.swing.JComboBox<String> assemblyGrade;
    private javax.swing.JLabel assemblyRemark;
    private javax.swing.JTextField assemblyUnits;
    private javax.swing.JButton calcGWA;
    private javax.swing.JComboBox<String> comprogGrade;
    private javax.swing.JLabel comprogRemark;
    private javax.swing.JTextField comprogUnits;
    private javax.swing.JComboBox<String> discreteGrade;
    private javax.swing.JLabel discreteRemark;
    private javax.swing.JTextField discreteUnits;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel finalgwaRemark;
    private javax.swing.JTextField firstnameTF;
    private javax.swing.JTable infoTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnameTF;
    private javax.swing.JTextField middlenameTF;
    private javax.swing.JComboBox<String> mmwGrade;
    private javax.swing.JLabel mmwRemark;
    private javax.swing.JTextField mmwUnits;
    private javax.swing.JComboBox<String> nstpGrade;
    private javax.swing.JLabel nstpRemark;
    private javax.swing.JTextField nstpUnits;
    private javax.swing.JComboBox<String> purcomGrade;
    private javax.swing.JLabel purcomRemark;
    private javax.swing.JTextField purcomUnits;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> sectionnameCB;
    private javax.swing.JComboBox<String> sinesosGrade;
    private javax.swing.JLabel sinesosRemark;
    private javax.swing.JTextField sinesosUnits;
    private javax.swing.JTextField studentnumberTF;
    private javax.swing.JTextField txtFinalGrade;
    // End of variables declaration//GEN-END:variables
}
