package act6_grp8;

class StudentInformation extends javax.swing.JFrame {

    /**
     * Creates new form StudentInformation
     */
    public StudentInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup1.add(rbtnMale);
        buttonGroup1.add(rbtnFemale);
        lblSex = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        lblHobbies = new javax.swing.JLabel();
        cbInternet = new javax.swing.JCheckBox();
        cbTV = new javax.swing.JCheckBox();
        chChat = new javax.swing.JCheckBox();
        cbGames = new javax.swing.JCheckBox();
        cbCook = new javax.swing.JCheckBox();
        cbMusic = new javax.swing.JCheckBox();
        lblCampus = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        cmbCampus = new javax.swing.JComboBox<>();
        lblStudentNo = new javax.swing.JLabel();
        lblCollege = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblProgram = new javax.swing.JLabel();
        txtStudentNo = new javax.swing.JTextField();
        cmbCollege = new javax.swing.JComboBox<>();
        txtLastName = new javax.swing.JTextField();
        cmbProgram = new javax.swing.JComboBox<>();
        txtFirstName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        txtMiddleName = new javax.swing.JTextField();
        scrllpAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        scrllpRegistered = new javax.swing.JScrollPane();
        tblRegistered = new javax.swing.JTable();
        lblMiddleName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 680));

        lblSex.setText("Sex:");

        rbtnMale.setText("Male");

        rbtnFemale.setText("Female");

        lblHobbies.setText("Hobbies:");

        cbInternet.setText("Browsing Internet");

        cbTV.setText("Watching TV");

        chChat.setText("Chatting");

        cbGames.setText("Playing Games");

        cbCook.setText("Cooking");

        cbMusic.setText("Listening to Music");

        lblCampus.setText("Campus");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Student Information");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmbCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABUCAY", "BALANGA", "DINALUPIHAN", "MAIN", "ORANI" }));
        cmbCampus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCampusItemStateChanged(evt);
            }
        });

        lblStudentNo.setText("Student No.:");

        lblCollege.setText("College");

        lblName.setText("Student Name:");

        lblProgram.setText("Program");

        cmbCollege.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        scrllpAddress.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrllpAddress.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        scrllpAddress.setViewportView(txtAddress);

        lblLastName.setText("Last Name");

        lblFirstName.setText("First Name");

        scrllpRegistered.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tblRegistered.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Number", "Student Name", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllpRegistered.setViewportView(tblRegistered);

        lblMiddleName.setText("Middle Name");

        lblAddress.setText("Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStudentNo)
                                .addGap(32, 32, 32)
                                .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblAddress)
                                    .addComponent(lblSex)
                                    .addComponent(lblHobbies)
                                    .addComponent(lblCampus)
                                    .addComponent(lblCollege)
                                    .addComponent(lblProgram))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbProgram, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(scrllpAddress)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRegister)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rbtnMale)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rbtnFemale))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cbInternet)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbTV)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(chChat))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(cbCook)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(cbGames))
                                                        .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbMusic))
                                                .addComponent(cmbCollege, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(scrllpRegistered))))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLastName)
                .addGap(132, 132, 132)
                .addComponent(lblFirstName)
                .addGap(125, 125, 125)
                .addComponent(lblMiddleName)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentNo)
                    .addComponent(txtStudentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(lblFirstName)
                    .addComponent(lblMiddleName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAddress)
                    .addComponent(scrllpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSex)
                    .addComponent(rbtnMale)
                    .addComponent(rbtnFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbInternet)
                    .addComponent(cbTV)
                    .addComponent(chChat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGames)
                    .addComponent(cbCook)
                    .addComponent(cbMusic)
                    .addComponent(lblHobbies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampus)
                    .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCollege)
                    .addComponent(cmbCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgram)
                    .addComponent(cmbProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrllpRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        studentNum = txtStudentNo.getText();
        name = txtFirstName.getText() + " " + txtMiddleName.getText() + " " + txtLastName.getText();
        program = cmbProgram.getItemAt(cmbProgram.getSelectedIndex());
        
        if (!studentNum.isBlank() || !txtFirstName.getText().isBlank() || !txtMiddleName.getText().isBlank() || !txtLastName.getText().isBlank() || !txtAddress.getText().isBlank() || buttonGroup1.getSelection() != null) {
        String studentData[] = {studentNum,name,program};
        
        javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) tblRegistered.getModel();
        tblModel.addRow(studentData);
        } else {
             javax.swing.JOptionPane.showMessageDialog(null, "Fill up all fields", "Missing Information", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cmbCampusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCampusItemStateChanged
        Classes classes = new Classes(evt);
        classes.aaaaa(evt);
    }//GEN-LAST:event_cmbCampusItemStateChanged

    public javax.swing.JButton getButton() {
        return btnRegister;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentInformation().setVisible(true);
        });
    }


    private String name;
    private String studentNum;
    private String program;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbCook;
    private javax.swing.JCheckBox cbGames;
    private javax.swing.JCheckBox cbInternet;
    private javax.swing.JCheckBox cbMusic;
    private javax.swing.JCheckBox cbTV;
    private javax.swing.JCheckBox chChat;
    public javax.swing.JComboBox<String> cmbCampus;
    public javax.swing.JComboBox<String> cmbCollege;
    public javax.swing.JComboBox<String> cmbProgram;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCampus;
    private javax.swing.JLabel lblCollege;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHobbies;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMiddleName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblStudentNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JScrollPane scrllpAddress;
    private javax.swing.JScrollPane scrllpRegistered;
    public javax.swing.JTable tblRegistered;
    private javax.swing.JTextArea txtAddress;
    public javax.swing.JTextField txtFirstName;
    public javax.swing.JTextField txtLastName;
    public javax.swing.JTextField txtMiddleName;
    public javax.swing.JTextField txtStudentNo;
    // End of variables declaration//GEN-END:variables
}

final class Classes extends java.util.ArrayList<String> {
    
    public Classes(java.awt.event.ItemEvent evt) {
        aaaaa(evt);
    }
    public void aaaaa(java.awt.event.ItemEvent evt) {
        StudentInformation info = new StudentInformation();
        info.cmbCampus.getSelectedItem();
        
        switch (info.toString()) {
            case "Main" : 
                info.cmbCollege.removeAllItems();
                info.cmbCollege.addItem("College of Engineering and Architecture");
                info.cmbCollege.addItem("College of Arts and Sciences");
                info.cmbCollege.addItem("College of Information and Communication Technology");
                info.cmbCollege.addItem("College of Technology");
                info.cmbCollege.addItem("College of Nursing");
                info.cmbCollege.getSelectedIndex();
                switch (info.toString()) {
                    case "0" : ;
                    case "1" : ;
                    case "2" : ;
                    case "3" : ;
                    case "4" : ;
                    default : ;
                }
            case "Balanga" : ;
            case "Dinalupihan" : ;
            case "Abucay" : ;
            case "Orani" : ;
            default : ;
            
        }
    }
}